name: My5Gcore Workflow
on:
  pull_request:
  push:
    branches:
      - master
      - develop

jobs:
  test:
    name: build and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      
      - name: Checkout Submodules
        uses: textbook/git-checkout-submodule-action@2.1.1
      
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14.10
        
      - name: Check Versions
        run: |
          lsb_release -a
          uname -a
          go version
          git --version
          docker --version
          echo "pwd: $(pwd)"
          echo "GOROOT: $GOROOT"
          echo "GOPATH: $GOPATH"
          echo "Listing dirs"
          ls -la
          sudo ln -s $GOROOT /usr/local/go
          
      - name: Install Go Deps
        run: go mod download
          
      - name: MongoDB
        uses: DigiPie/mongo-action@v1.0.0
        with:
          image_version: latest
          port: 27017
          
      - name: Packages Control Plane
        run: |
          sudo apt -y -q update
          sudo apt -y -q install wget git
          
      - name: Packages User Plane
        run: | 
          sudo apt -y update
          sudo apt -y install git gcc cmake autoconf libtool pkg-config libmnl-dev libyaml-dev
          go get -u github.com/sirupsen/logrus
          gcc --version

      - name: GTP5G module
        run: | 
          uname -r
          git clone -b v0.2.0 https://github.com/PrinzOwO/gtp5g.git
          cd gtp5g
          make
          sudo make install    
          lsmod | grep gtp

      - name: Build NFs
        run: sudo make -f Makefile-CI all
          
      - name: TestRegistration
        run: |
          chmod +x test.sh
          sudo ./test.sh TestRegistration
        timeout-minutes: 3
      
      - name: TestGUTIRegistration
        run: sleep 7 && sudo ./test.sh TestGUTIRegistration
        timeout-minutes: 3
        
      - name: TestServiceRequest
        run: sleep 7 && sudo ./test.sh TestRegistration
        timeout-minutes: 3
      
      - name: TestXnHandover
        run: sleep 7 && sudo ./test.sh TestXnHandover
        timeout-minutes: 3
      
      - name: TestN2Handover
        run: sleep 7 && sudo ./test.sh TestN2Handover
        timeout-minutes: 3
         
      - name: TestDeregistration
        run: sleep 7 && sudo ./test.sh TestDeregistration
        timeout-minutes: 3
         
      - name: TestPDUSessionReleaseRequest
        run: sleep 7 && sudo ./test.sh TestPDUSessionReleaseRequest
        timeout-minutes: 3
         
      - name: TestPaging
        run: sleep 7 && sudo ./test.sh TestPaging
        timeout-minutes: 3
       
      - name: TestNon3GPP
        run: sleep 7 && sudo ./test.sh TestNon3GPP
        timeout-minutes: 3

      - name: TestReSynchronisation
        run: sleep 7 && sudo ./test.sh TestReSynchronisation
        timeout-minutes: 3
